
[project]
name = "banana-nft-swap"

[contracts.ft-trait]
path = "contracts/external/ft-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/external/nft-trait.clar"
depends_on = []

[contracts.fun-nft]
path = "contracts/external/fun-nft.clar"
depends_on = []

[contracts.fixed-fees]
path = "contracts/fixed-fees.clar"
depends_on = []


[contracts.bitcoin-monkeys-bananas]
path = "contracts/external/bitcoin-monkeys-bananas.clar"
depends_on = ["ft-trait"]

[contracts.banana-nft-swap]
path = "contracts/banana-nft-swap.clar"
depends_on = ["bitcoin-monkeys-bananas", "nft-trait"]


[notebooks]
