
[project]
name = "Friedger token"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"


[contracts.friedger]
path = "contracts/friedger.clar"
depends_on = []

[notebooks]
