
[project]
name = "banana-nft-swap"

[contracts.ft-trait]
path = "contracts/external/ft-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/external/nft-trait.clar"
depends_on = []

[contracts.fun-nft]
path = "contracts/external/fun-nft.clar"
depends_on = []

[contracts.fun-token]
path = "contracts/external/fun-token.clar"
depends_on = []

[contracts.fixed-fees]
path = "contracts/fixed-fees.clar"
depends_on = ["miamicoin-token"]


[contracts.miamicoin-token]
path = "contracts/external/miamicoin-token.clar"
depends_on = ["ft-trait"]

[contracts.mia-nft-swap]
path = "contracts/mia-nft-swap.clar"
depends_on = ["miamicoin-token", "nft-trait"]

[contracts.mia-ft-swap]
path = "contracts/mia-ft-swap.clar"
depends_on = ["miamicoin-token", "ft-trait"]


[notebooks]
