
[project]
name = "xbtc-swap"

[contracts.ft-trait]
path = "contracts/external/ft-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/external/nft-trait.clar"
depends_on = []

[contracts.fun-nft]
path = "contracts/external/fun-nft.clar"
depends_on = []

[contracts.fun-token]
path = "contracts/external/fun-token.clar"
depends_on = []

[contracts.fixed-fees]
path = "contracts/fixed-fees.clar"
depends_on = ["Wrapped-Bitcoin"]


[contracts.Wrapped-Bitcoin]
path = "contracts/external/Wrapped-Bitcoin.clar"
depends_on = ["ft-trait"]

[contracts.xbtc-nft-swap]
path = "contracts/xbtc-nft-swap.clar"
depends_on = ["Wrapped-Bitcoin", "nft-trait"]

[contracts.xbtc-ft-swap]
path = "contracts/xbtc-ft-swap.clar"
depends_on = ["Wrapped-Bitcoin", "ft-trait"]


[notebooks]
