
[project]
name = "banana-nft-swap"

[contracts.ft-trait]
path = "contracts/external/ft-trait.clar"
depends_on = []

[contracts.nft-trait]
path = "contracts/external/nft-trait.clar"
depends_on = []

[contracts.fun-nft]
path = "contracts/external/fun-nft.clar"
depends_on = []

[contracts.fun-token]
path = "contracts/external/fun-token.clar"
depends_on = []

[contracts.fixed-fees]
path = "contracts/fixed-fees.clar"
depends_on = ["btc-monkeys-bananas"]


[contracts.btc-monkeys-bananas]
path = "contracts/external/btc-monkeys-bananas.clar"
depends_on = ["ft-trait"]

[contracts.banana-nft-swap]
path = "contracts/banana-nft-swap.clar"
depends_on = ["btc-monkeys-bananas", "nft-trait"]

[contracts.banana-ft-swap]
path = "contracts/banana-ft-swap.clar"
depends_on = ["btc-monkeys-bananas", "ft-trait"]


[notebooks]
